CREATE  VIEW user_and_complaint AS
  SELECT
    USER_ID,
    USER_NAME,
    NAME,
    SURNAME,
    AGE,
    COMPLAINT_ID,
    SUBJECT
	

  FROM COMPLAINTS NATURAL JOIN USERS
  
  CREATE  VIEW details_sale_record AS
  SELECT
    S.RECORD_ID,
    A.ANNOUNCEMENT_ID,
    A.PRICE,
    SELLER.USER_ID   SELLER_ID,
    BUYER.USER_ID    BUYER_ID,
    A.TITLE,
    SELLER.USER_NAME SELLER,
    BUYER.USER_NAME  BUYER
  FROM ANNOUNCEMENTS A, SALE_RECORDS S, USERS BUYER, USERS SELLER
  WHERE A.ANNOUNCEMENT_ID = S.ANNOUNCEMENT_ID   AND S.SELLER_ID = SELLER.USER_ID AND S.BUYER_ID = BUYER.USER_ID

  
  CREATE  VIEW sub_admin_details AS
  SELECT *
  FROM subadmins NATURAL JOIN USERS;
 

  
  
CREATE VIEW announcement_details AS
  SELECT
    A.*,
    CA.NAME AS CITY_NAME,
    CI.NAME AS CATEGORY_NAME
  FROM ANNOUNCEMENTS A, PRODUCTS P, CATEGORIES CA, CITIES CI
  WHERE A.PRODUCT_ID = P.PRODUCT_ID  AND P.CATEGORY_ID = CA.CATEGORY_ID AND A.CITY_ID = CI.CITY_ID



